


export interface PackageItem {
    id: string;
    title: string;
    category:
    | 'Hajj'                // General Hajj
    | 'Economy Hajj'        // Economy Hajj
    | 'Standard Hajj'       // Standard Hajj
    | 'Premium Hajj'        // Premium Hajj
    | 'VIP Special Hajj'    // VIP Special Hajj
    | 'Economy Umrah'       // Regular Umrah Categories
    | 'Standard Umrah'
    | 'Premium Umrah'
    | 'VIP Special Umrah'
    | 'Ramadan';            // Only Ramadan (Hajj ছাড়া)
    badge?: string;
    imageUrl: string;
    makkahHotel: string;
    madinahHotel: string;
    makkahDistance: string;
    madinahDistance: string;
    durationDays: number;
    sharingType: string;
    pricePerPerson: number;
    inclusions: string[];
}

export const ALL_PACKAGES: PackageItem[] = [
    // --- HAJJ PACKAGES ---
    {
        id: 'hajj-gen-1',
        title: '30 Days Complete Pilgrim Hajj Package',
        category: 'Hajj',
        badge: 'Government Approved',
        imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Al Eiman Royal or Similar',
        madinahHotel: 'Saja Al Madinah or Similar',
        makkahDistance: '1500m (Shuttle Bus Service)',
        madinahDistance: '400m Walking',
        durationDays: 30,
        sharingType: 'Quad (4 Person)',
        pricePerPerson: 580000,
        inclusions: ['Hajj Visa & Draft', 'Direct Flight Ticket', 'Mina & Arafat Tent Tents', 'Qurbani Included', 'Guide & Muallim Service'],
    },
    {
        id: 'hajj-eco-1',
        title: '40 Days Long Economy Hajj Journey',
        category: 'Economy Hajj',
        badge: 'Budget Hajj',
        imageUrl: 'https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Azizia Building / Shifting Hotel',
        madinahHotel: 'Ansar Palace or Similar',
        makkahDistance: 'Shifting to Mina/Haram Shuttle',
        madinahDistance: '600m Walking',
        durationDays: 40,
        sharingType: '5/6 Person Sharing',
        pricePerPerson: 520000,
        inclusions: ['Hajj Visa', 'Return Flight', 'Category D Mina Tents', '3 Meals Daily in Azizia', 'Medical Support'],
    },
    {
        id: 'hajj-std-1',
        title: '25 Days Standard Shifting Hajj Comfort',
        category: 'Standard Hajj',
        badge: 'Most Popular',
        imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',        makkahHotel: 'Swissotel Al Maqam (Non-Shifting Period)',
        madinahHotel: 'Grand Plaza Madinah',
        makkahDistance: 'Direct Clock Tower',
        madinahDistance: '300m Walking',
        durationDays: 25,
        sharingType: 'Triple Sharing',
        pricePerPerson: 750000,
        inclusions: ['Hajj Visa & Insurance', 'Direct Biman/Saudi Airline', 'Upgraded Category C Mina Tents', 'Buffet Meals', 'Scholarly Guidance'],
    },
    {
        id: 'hajj-prm-1',
        title: '15 Days Non-Shifting Express Premium Hajj',
        category: 'Premium Hajj',
        badge: '5-Star Luxury',
        imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Fairmont Makkah Clock Royal Tower',
        madinahHotel: 'Dar Al Taqwa Madinah',
        makkahDistance: '0m Direct Haram Access',
        madinahDistance: '0m Front View',
        durationDays: 15,
        sharingType: 'Double Room',
        pricePerPerson: 115000,
        inclusions: ['VIP Express Visa', 'Business Class Option', 'AC European Gypsum Mina Tents', 'Private Transport', 'Full Board Buffet'],
    },
    {
        id: 'hajj-vip-1',
        title: '14 Days Royal VIP Special Non-Shifting Hajj',
        category: 'VIP Special Hajj',
        badge: 'VIP Presidential',
        imageUrl: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Raffles Makkah Palace',
        madinahHotel: 'Oberoi Madinah',
        makkahDistance: '0m Panoramic Kaaba View',
        madinahDistance: '0m Green Dome View',
        durationDays: 14,
        sharingType: 'Private Suite',
        pricePerPerson: 1650000,
        inclusions: ['VIP Private Camp Mina', 'Dedicated Butler & Muallim', 'GMC Private Fleet', 'First Class Flights', 'Helipad Access Option'],
    },

    // --- ECONOMY UMRAH (6 Packages) ---
    {
        id: 'eco-1',
        title: '14 Days Basic Umrah Savings',
        category: 'Economy Umrah',
        badge: 'Best Saver',
        imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',        makkahHotel: 'Kiswah Towers or Similar',
        madinahHotel: 'Ansar Palace or Similar',
        makkahDistance: '900m (Free Shuttle Bus)',
        madinahDistance: '600m Walking',
        durationDays: 14,
        sharingType: 'Quad (4 Person)',
        pricePerPerson: 135000,
        inclusions: ['Umrah Visa', 'Direct Flight Ticket', 'Shuttle Service', 'Ziyarah Tours', 'Group Guide'],
    },
    {
        id: 'eco-2',
        title: '10 Days Budget Umrah Express',
        category: 'Economy Umrah',
        imageUrl: 'https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Al Shohada Economy',
        madinahHotel: 'Manazel Al Falah',
        makkahDistance: '1000m (Shuttle)',
        madinahDistance: '700m Walking',
        durationDays: 10,
        sharingType: 'Quad (4 Person)',
        pricePerPerson: 125000,
        inclusions: ['Umrah Visa', 'Return Airfare', 'Hotel Accommodation', 'Ground Transport'],
    },
    {
        id: 'eco-3',
        title: '15 Days Family Budget Package',
        category: 'Economy Umrah',
        badge: 'Family Special',
         imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Luluat Al Sharq',
        madinahHotel: 'Badr Al Masaa',
        makkahDistance: '850m Walking',
        madinahDistance: '500m Walking',
        durationDays: 15,
        sharingType: 'Triple (3 Person)',
        pricePerPerson: 145000,
        inclusions: ['Umrah Visa', 'Flight Tickets', 'Makkah/Madinah Ziyarah', '24/7 Support'],
    },
    {
        id: 'eco-4',
        title: '21 Days Extended Economy Journey',
        category: 'Economy Umrah',
        imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Zero One Hotel',
        madinahHotel: 'Al Ansar Golden',
        makkahDistance: '1200m (Shuttle)',
        madinahDistance: '800m Walking',
        durationDays: 21,
        sharingType: 'Quad (4 Person)',
        pricePerPerson: 165000,
        inclusions: ['Umrah Visa', 'Economy Flight', 'Group Transport', 'Ziyarah Included'],
    },
    {
        id: 'eco-5',
        title: '7 Days Short Economy Break',
        category: 'Economy Umrah',
        imageUrl: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Al Fajr Al Badee',
        madinahHotel: 'Al Mukhtara International',
        makkahDistance: '950m Shuttle',
        madinahDistance: '650m Walking',
        durationDays: 7,
        sharingType: 'Double (2 Person)',
        pricePerPerson: 120000,
        inclusions: ['Visa Processing', 'Direct Airfare', 'Hotel Stay', 'Airport Transfer'],
    },
    {
        id: 'eco-6',
        title: '14 Days Group Saver Package',
        category: 'Economy Umrah',
        badge: 'Popular Group',
         imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Mawaddah Al Baraka',
        madinahHotel: 'Mawaddah Al Safwa',
        makkahDistance: '900m Shuttle',
        madinahDistance: '550m Walking',
        durationDays: 14,
        sharingType: 'Quad (4 Person)',
        pricePerPerson: 138000,
        inclusions: ['Visa & Insurance', 'Air Tickets', 'Group Transport', 'Guide Service'],
    },

    // --- STANDARD UMRAH (6 Packages) ---
    {
        id: 'std-1',
        title: '14 Days Deluxe Comfort Package',
        category: 'Standard Umrah',
        badge: 'Most Popular',
         imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Swissotel Al Maqam (4-Star)',
        madinahHotel: 'Saja Al Madinah (4-Star)',
        makkahDistance: 'Direct Clock Tower',
        madinahDistance: '350m Central Northern Area',
        durationDays: 14,
        sharingType: 'Triple Sharing',
        pricePerPerson: 185000,
        inclusions: ['Saudi Tourist/Umrah Visa', 'Buffet Breakfast', 'VIP Transport AC Bus', 'Historical Ziyarah'],
    },
    {
        id: 'std-2',
        title: '10 Days Executive Standard Stay',
        category: 'Standard Umrah',
        imageUrl: 'https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Pullman Zamzam Makkah',
        madinahHotel: 'Grand Plaza Madinah',
        makkahDistance: '0m Clock Tower Plaza',
        madinahDistance: '300m Walking',
        durationDays: 10,
        sharingType: 'Double Sharing',
        pricePerPerson: 195000,
        inclusions: ['Visa with Insurance', 'Direct Biman/Saudi Airline', 'Buffet Breakfast', 'Private Car Transfer Option'],
    },
    {
        id: 'std-3',
        title: '15 Days Makkah First Standard',
        category: 'Standard Umrah',
        imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Makkah Hotel & Towers',
        madinahHotel: 'Leader Al Maktara',
        makkahDistance: 'Adjacent to Haram',
        madinahDistance: '400m Walking',
        durationDays: 15,
        sharingType: 'Quad Sharing',
        pricePerPerson: 175000,
        inclusions: ['Full Visa Processing', 'Round Trip Air Ticket', 'AC Bus Service', 'Comprehensive Ziyarah'],
    },
    {
        id: 'std-4',
        title: '12 Days Family Comfort Standard',
        category: 'Standard Umrah',
        badge: 'Recommended',
        imageUrl: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Voco Makkah (IHG)',
        madinahHotel: 'Golden Tulip Al Shakreen',
        makkahDistance: '500m (Dedicated Shuttle)',
        madinahDistance: '250m Walking',
        durationDays: 12,
        sharingType: 'Double Sharing',
        pricePerPerson: 189000,
        inclusions: ['Visa + Insurance', 'Buffet Breakfast', 'Ziyarah Tours', '24/7 Scholar Guidance'],
    },
    {
        id: 'std-5',
        title: '14 Days Madinah First Standard',
        category: 'Standard Umrah',
         imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Le Meridien Makkah',
        madinahHotel: 'Zowar International',
        makkahDistance: '300m Walking',
        madinahDistance: '200m Walking',
        durationDays: 14,
        sharingType: 'Triple Sharing',
        pricePerPerson: 182000,
        inclusions: ['Umrah Visa', 'Airlines Ticket', 'Breakfast Included', 'Intercity Transfers'],
    },
    {
        id: 'std-6',
        title: '10 Days Weekend Standard Trip',
        category: 'Standard Umrah',
         imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Rayhaan by Rotana',
        madinahHotel: 'Al Aqeeq Madinah',
        makkahDistance: 'Direct Haram View',
        madinahDistance: '300m Gate 25',
        durationDays: 10,
        sharingType: 'Double Sharing',
        pricePerPerson: 198000,
        inclusions: ['Fast-track Visa', 'Direct Flight', 'Hotel + Breakfast', 'Private Transport'],
    },

    // --- PREMIUM UMRAH (6 Packages) ---
    {
        id: 'prm-1',
        title: '14 Days Royal Clock Tower VIP',
        category: 'Premium Umrah',
        badge: '5-Star Luxury',
        imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Raffles Makkah Palace',
        madinahHotel: 'Oberoi Madinah',
        makkahDistance: '0m Courtyard Facing Haram',
        madinahDistance: '0m Facing Prophet Mosque',
        durationDays: 14,
        sharingType: 'Double / Private Suite',
        pricePerPerson: 320000,
        inclusions: ['VIP Express Visa', 'Business Class Flight Option', 'GMC Private Transport', '5-Star Full Board Buffet', 'Private Muallim'],
    },
    {
        id: 'prm-2',
        title: '10 Days Fairmont Haram View VIP',
        category: 'Premium Umrah',
        badge: 'Haram View',
        imageUrl: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Fairmont Makkah Clock Royal',
        madinahHotel: 'Dar Al Taqwa Madinah',
        makkahDistance: '0m Direct Courtyard',
        madinahDistance: '0m Ladies Gate Facing',
        durationDays: 10,
        sharingType: 'Double Room',
        pricePerPerson: 295000,
        inclusions: ['VIP Visa', 'Direct Airlines Ticket', 'Private Luxury Sedan', 'Full Board Meal'],
    },
    {
        id: 'prm-3',
        title: '15 Days Signature Luxury Umrah',
        category: 'Premium Umrah',
         imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Jumeirah Jabal Omar',
        madinahHotel: 'Madinah Hilton',
        makkahDistance: '0m Front Courtyard',
        madinahDistance: '50m Main Plaza',
        durationDays: 15,
        sharingType: 'Double Room',
        pricePerPerson: 310000,
        inclusions: ['Instant Visa Approval', 'First Class Air Ticket', 'Private VIP GMC', '5-Star Breakfast & Dinner'],
    },
    {
        id: 'prm-4',
        title: '7 Days Executive VIP Retreat',
        category: 'Premium Umrah',
        badge: 'Express VIP',
         imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Address Jabal Omar Makkah',
        madinahHotel: 'Anwar Al Madinah Movenpick',
        makkahDistance: '0m Direct Sky Bridge Access',
        madinahDistance: 'Direct Plaza Entry',
        durationDays: 7,
        sharingType: 'Single/Double Suite',
        pricePerPerson: 275000,
        inclusions: ['E-Visa VIP', 'Business Class Flight', 'Private Airport Chauffeur', 'Luxury Buffet'],
    },
    {
        id: 'prm-5',
        title: '14 Days Conrad & Intercontinental VIP',
        category: 'Premium Umrah',
        imageUrl: 'https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Conrad Makkah Jabal Omar',
        madinahHotel: 'InterContinental Dar Al Iman',
        makkahDistance: '0m Steps to Haram',
        madinahDistance: '0m Prophet Mosque Courtyard',
        durationDays: 14,
        sharingType: 'Double Suite',
        pricePerPerson: 340000,
        inclusions: ['Express Visa', 'Five Star Accommodation', 'Private GMC Luxury Van', 'Historical VIP Ziyarah'],
    },
    {
        id: 'prm-6',
        title: '12 Days Royal Presidential Suite Package',
        category: 'Premium Umrah',
        badge: 'Presidential',
        imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Swissotel Makkah (Presidential)',
        madinahHotel: 'Pullman Zamzam Madinah',
        makkahDistance: '0m Direct Elevator to Haram',
        madinahDistance: '100m Central Zone',
        durationDays: 12,
        sharingType: 'Suite Room',
        pricePerPerson: 350000,
        inclusions: ['VIP Concierge Visa', 'Emirates/Saudi Business Class', 'Private Luxury GMC', 'Dedicated 24/7 Butler'],
    },

    // --- RAMADAN (6 Packages) ---
    {
        id: 'ram-1',
        title: '30 Days Full Month Ramadan Blessings',
        category: 'Ramadan',
        badge: 'Full Ramadan',
         imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Makkah Hotel Complex',
        madinahHotel: 'Saja Al Madinah',
        makkahDistance: 'Direct Haram Plaza',
        madinahDistance: '300m Central Area',
        durationDays: 30,
        sharingType: 'Quad / Family',
        pricePerPerson: 380000,
        inclusions: ['Special Ramadan Visa', 'Sahur & Iftar Meals', 'Direct Airfare', 'Full Month Guidance & Ziyarah'],
    },
    {
        id: 'ram-2',
        title: '15 Days 1st Laylatul Qadr Special (Last 10 Days)',
        category: 'Ramadan',
        badge: 'Last 10 Days',
         imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Swissotel Al Maqam',
        madinahHotel: 'Al Aqeeq Madinah',
        makkahDistance: '0m Clock Tower',
        madinahDistance: '200m Walking',
        durationDays: 15,
        sharingType: 'Triple Sharing',
        pricePerPerson: 395000,
        inclusions: ['Ramadan Visa Stamping', 'Iftar Buffet Included', 'Direct Biman Air Ticket', '24/7 Scholar Support'],
    },
    {
        id: 'ram-3',
        title: '14 Days 1st Half Ramadan Spiritual',
        category: 'Ramadan',
        imageUrl: 'https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Kiswah Towers Ramadan Suite',
        madinahHotel: 'Leader Al Maktara',
        makkahDistance: '900m Shuttle Bus',
        madinahDistance: '400m Walking',
        durationDays: 14,
        sharingType: 'Quad Sharing',
        pricePerPerson: 220000,
        inclusions: ['Ramadan Visa', 'Roundtrip Flight', 'Iftar Arrangement', 'Group Transport'],
    },
    {
        id: 'ram-4',
        title: '10 Days Mid-Ramadan Express',
        category: 'Ramadan',
        imageUrl: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Voco Makkah',
        madinahHotel: 'Grand Plaza Madinah',
        makkahDistance: '500m Shuttle',
        madinahDistance: '300m Walking',
        durationDays: 10,
        sharingType: 'Triple Sharing',
        pricePerPerson: 245000,
        inclusions: ['Fast Ramadan Visa', 'Direct Flight Ticket', 'Sahur Buffets', 'Ziyarah Included'],
    },
    {
        id: 'ram-5',
        title: '15 Days Ramadan & Eid in Makkah',
        category: 'Ramadan',
        badge: 'Eid Special',
        imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Pullman Zamzam Makkah',
        madinahHotel: 'Dar Al Taqwa',
        makkahDistance: '0m Clock Tower Plaza',
        madinahDistance: '0m Gate 25',
        durationDays: 15,
        sharingType: 'Double Sharing',
        pricePerPerson: 420000,
        inclusions: ['Visa Processing', 'Eid Prayer at Haram', 'Luxury Hotel Stay', 'Private Car Transfer'],
    },
    {
        id: 'ram-6',
        title: '30 Days Budget Full Ramadan',
        category: 'Ramadan',
         imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Al Shohada Economy',
        madinahHotel: 'Ansar Palace',
        makkahDistance: '1000m Dedicated Shuttle',
        madinahDistance: '600m Walking',
        durationDays: 30,
        sharingType: 'Quad Sharing',
        pricePerPerson: 295000,
        inclusions: ['Full Month Visa', 'Budget Flights', 'Sahur Assistance', 'AC Bus Transfers'],
    },

    // --- VIP SPECIAL UMRAH (6 Packages) ---
    {
        id: 'vip-1',
        title: '14 Days Private Helipad & Suite VIP',
        category: 'VIP Special Umrah',
        badge: 'Ultra Luxury',
        imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Raffles Royal Suite',
        madinahHotel: 'Oberoi Presidential',
        makkahDistance: '0m Panoramic Kaaba View',
        madinahDistance: '0m Green Dome View',
        durationDays: 14,
        sharingType: 'Private Family Suite',
        pricePerPerson: 550000,
        inclusions: ['Helipad Airport Transfer Option', 'Private Chef & Butler', 'Private GMC Fleet', 'VIP Fast-track Visa'],
    },
    {
        id: 'vip-2',
        title: '10 Days Custom Private Family Jet',
        category: 'VIP Special Umrah',
        imageUrl: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Fairmont Presidential Suite',
        madinahHotel: 'Dar Al Taqwa Suite',
        makkahDistance: '0m Kaaba View',
        madinahDistance: '0m Front View',
        durationDays: 10,
        sharingType: 'Private Suite',
        pricePerPerson: 480000,
        inclusions: ['Private Chauffeur', '5-Star Full Board Custom Menu', 'VIP Escort', 'Express Visa'],
    },
    {
        id: 'vip-3',
        title: '12 Days Direct Kaaba View Signature VIP',
        category: 'VIP Special Umrah',
        badge: 'Kaaba View',
         imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Swissotel Royal Suite',
        madinahHotel: 'Madinah Hilton Presidential',
        makkahDistance: '0m Full Kaaba Facing',
        madinahDistance: '50m Main Plaza',
        durationDays: 12,
        sharingType: 'Private Double Suite',
        pricePerPerson: 450000,
        inclusions: ['Dedicated Personal Guide', 'Private GMC Yukon XL', 'Full Board Catering', 'VIP Visa'],
    },
    {
        id: 'vip-4',
        title: '15 Days Scholar Guided VIP Pilgrimage',
        category: 'VIP Special Umrah',
         imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Address Jabal Omar Suite',
        madinahHotel: 'InterContinental Dar Al Iman',
        makkahDistance: '0m Courtyard',
        madinahDistance: '0m Courtyard',
        durationDays: 15,
        sharingType: 'Double Room',
        pricePerPerson: 420000,
        inclusions: ['Renowned Scholar Escort', 'Private Luxury Bus', '5-Star Dining', 'Historical Deep Tour'],
    },
    {
        id: 'vip-5',
        title: '7 Days Executive Royal Express',
        category: 'VIP Special Umrah',
        badge: 'Executive',
        imageUrl: 'https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Jumeirah Royal Penthouse',
        madinahHotel: 'Oberoi Suite',
        makkahDistance: '0m Courtyard Access',
        madinahDistance: '0m Facing Haram',
        durationDays: 7,
        sharingType: 'Private Penthouse',
        pricePerPerson: 390000,
        inclusions: ['First Class Air Tickets', 'Private Airport Lounge Access', 'Luxury Sedan', 'Custom Itinerary'],
    },
    {
        id: 'vip-6',
        title: '21 Days Ultimate Royal Spiritual Retreat',
        category: 'VIP Special Umrah',
        imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&q=80&w=800',
        makkahHotel: 'Conrad Royal Suite',
        madinahHotel: 'Pullman Zamzam Suite',
        makkahDistance: '0m Direct Entry',
        madinahDistance: '100m Central Zone',
        durationDays: 21,
        sharingType: 'Family Suite',
        pricePerPerson: 510000,
        inclusions: ['Full VIP Concierge', 'Private Chauffeur 24/7', 'Five Star Full Board', 'Comprehensive Visa & Insurance'],
    },
];